name: Deploy Public Health Tracker to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Docker build context
        run: ls -la ./public-health-tracker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/public-health-tracker
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKERHUB_REPO:$IMAGE_TAG ./public-health-tracker
          docker push $DOCKERHUB_REPO:$IMAGE_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubernetes deployment in Amazon EKS
        env:
          EKS_CLUSTER: public-health-cluster
          KUBE_DEPLOYMENT: public-health-app
          DOCKERHUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/public-health-tracker
          IMAGE_TAG: latest
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER
          kubectl set image deployment/$KUBE_DEPLOYMENT public-health-container=$DOCKERHUB_REPO:$IMAGE_TAG
          kubectl rollout status deployment/$KUBE_DEPLOYMENT
